[profile.default]
src = 'contracts'
out = 'artifacts_forge'
cache_path  = 'cache_forge'
test = 'tests_forge'
libs = ['node_modules', 'lib']


remappings = [
    '@openzeppelin=node_modules/@openzeppelin/',
    '@erc6551=node_modules/erc6551/',
    'hardhat/=node_modules/hardhat/',
    'forge-std/=lib/forge-std/src/'
]